import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/utils";
import { Toaster } from "react-hot-toast";

const mulishFont = Mulish({
    subsets: ["latin"],
    weight: ["300", "400", "700"]
});

export const metadata: Metadata = {
    title: "Task Tracker",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="light">
            <body
                className={cn(
                    "bg-gradient-to-br from-blue-100 via-white to-blue-50",
                    mulishFont.className
                )}
            >
                {children}
                <Toaster position="bottom-center" reverseOrder={false} />
            </body>
        </html>
    );
}
